Update README.md
Serious-senpai/synchronization-problems pull request #3
Opened 2024-05-07 15:35 UTC by Flogas0833

![angry](https://github.com/Serious-senpai/synchronization-problems/assets/149156689/1961716c-bbc4-4a08-a29c-7fa9f21805aa)

2024-05-08 00:27 UTC, Serious-senpai commented
Phần code nên dùng `<thread>` hay `CreateThread` của win32 API nhỉ?

2024-05-08 02:00 UTC, Flogas0833 commented
Sao tôi biết :) cứ duyệt đi

2024-05-11 04:29 UTC, Serious-senpai requested changes
Update code đi em

2024-05-11 04:29 UTC, Serious-senpai commented on README.md
> +
```suggestion
#include <chrono>
#include <iostream>
#include <random>
#include <windows.h>

std::mt19937 rng(std::chrono::steady_clock::now().time_since_epoch().count());

template <typename T>
T random_int(const T l, const T r)
{
    std::uniform_int_distribution<T> unif(l, r);
    return unif(rng);
}

HANDLE smoking;
std::vector<HANDLE> semaphores;

void synchronization_primitives()
{
    smoking = CreateSemaphoreW(NULL, 0, 1, NULL);
    for (int i = 0; i < 3; i++)
    {
        semaphores.push_back(CreateSemaphoreW(NULL, 0, 1, NULL));
    }
}

DWORD WINAPI agent(void *)
{
    while (true)
    {
        int ingredient = random_int(0, 2), next_ingredient = (1 + ingredient) % 3;
        std::cout << "Got ingredients " << ingredient << ", " << next_ingredient << std::endl;

        ReleaseSemaphore(semaphores[ingredient], 1, NULL);
        ReleaseSemaphore(semaphores[next_ingredient], 1, NULL);
        WaitForSingleObject(smoking, INFINITE);
    }

    return 0;
}

DWORD WINAPI smoker(void *ptr)
{
    int ingredient = *(int *)ptr;
    while (true)
    {
        WaitForSingleObject(semaphores[(ingredient + 1) % 3], INFINITE);
        std::cout << "Smoker " << ingredient << " got " << (ingredient + 1) % 3 << std::endl;
        WaitForSingleObject(semaphores[(ingredient + 2) % 3], INFINITE);
        std::cout << "Smoker " << ingredient << " got " << (ingredient + 2) % 3 << std::endl;
        std::cout << "Smoker " << ingredient << " is smoking" << std::endl;
        Sleep(500);
        std::cout << "Smoker " << ingredient << " is done" << std::endl;
        ReleaseSemaphore(smoking, 1, NULL);
    }

    return 0;
}

int main()
{
    synchronization_primitives();

    std::vector<HANDLE> threads;
    threads.push_back(
        CreateThread(
            NULL,   // lpThreadAttributes
            0,      // dwStackSize
            &agent, // lpStartAddress
            NULL,   // lpParameter
            0,      // dwCreationFlags
            NULL)   // lpThreadId
    );

    int *ingredient_ptr[3];
    for (int i = 0; i < 3; i++)
    {
        ingredient_ptr[i] = new int(i);
        threads.push_back(
            CreateThread(
                NULL,              // lpThreadAttributes
                0,                 // dwStackSize
                &smoker,           // lpStartAddress
                ingredient_ptr[i], // lpParameter
                0,                 // dwCreationFlags
                NULL)              // lpThreadId
        );
    }

    for (auto &thread : threads)
    {
        WaitForSingleObject(thread, INFINITE);
        CloseHandle(thread);
    }

    for (int i = 0; i < 3; i++)
    {
        delete ingredient_ptr[i];
    }

    return 0;
}
```

2024-05-11 04:32 UTC, Serious-senpai approved these changes

2024-05-11 04:33 UTC, merged